image:
  pullPolicy: Always
  repository: nginx
  tag: this-tag-does-not-exist-99999
replicaCount: 1
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu:
      requests:
        cpu: 200m
        memory: 1Gi
    memory: 64Mi
