image:
  pullPolicy: IfNotPresent
  repository: nginx
  tag:
  - image: null
    tag: v1.21
replicaCount: 1
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
